import 'package:garden/models/data.dart';

import './models/category.dart';

const DummyDataCategory = const [
  Category(
    id: 'p1',
    title: 'Plants',
    imageurl: 'https://img.icons8.com/dotty/2x/potted-plant.png',
  ),
  Category(
    id: 'p2',
    title: 'Bonsai',
    imageurl: 'https://img.icons8.com/dotty/2x/bonsai.png',
  ),
  Category(
    id: 'p3',
    title: 'Seeds',
    imageurl: 'https://img.icons8.com/dotty/2x/potted-plant.png',
  ),
  Category(
    id: 'p4',
    title: 'Tools',
    imageurl: 'https://img.icons8.com/dotty/2x/spade.png',
  ),
  Category(
    id: 'p5',
    title: 'accessories',
    imageurl: 'https://img.icons8.com/dotty/2x/edit.png',
  ),
  Category(
    id: 'p6',
    title: 'Soil',
    imageurl: 'https://img.icons8.com/dotty/2x/soil.png',
  ),
];

const DummyData = [
  Data(
    id: 'i1',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i12',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i2',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i24',
    catid: 'p3',
    title: 'Verbena Quartz',
    description: 'Verbena is one of those garden essentials that bloom from spring to fall with very little fuss. 1 packet contains - 3gm / 10gm seeds.',
    price: 100,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-verbena-quartz-mix-colors3.jpg',
  ),
  Data(
    id: 'i3',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i4',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i5',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i6',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i7',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i8',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i9',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i10',
    catid: 'p1',
    title: 'Umbrella Palm',
    description: 'Table palm easily grows in the indoor condition in the young stage of palm with low maintenance.',
    price: 250,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-table-palm-umbrella-palm-2.jpg',
  ),
  Data(
    id: 'i11',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  
  Data(
    id: 'i13',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i14',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i15',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i16',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i17',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i18',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i19',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i20',
    catid: 'p2',
    title: 'Jade Bonsai',
    description: 'Bonsai is closely resembling circumstances in nature. These styles are open to personal interpretation and creativity of nature.',
    price: 2500,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-jade-bonsai-formal-upright-style-plant-1.jpg',
  ),
  Data(
    id: 'i21',
    catid: 'p3',
    title: 'Verbena Quartz',
    description: 'Verbena is one of those garden essentials that bloom from spring to fall with very little fuss. 1 packet contains - 3gm / 10gm seeds.',
    price: 100,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-verbena-quartz-mix-colors3.jpg',
  ),
  Data(
    id: 'i22',
    catid: 'p3',
    title: 'Verbena Quartz',
    description: 'Verbena is one of those garden essentials that bloom from spring to fall with very little fuss. 1 packet contains - 3gm / 10gm seeds.',
    price: 100,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-verbena-quartz-mix-colors3.jpg',
  ),
  Data(
    id: 'i23',
    catid: 'p3',
    title: 'Verbena Quartz',
    description: 'Verbena is one of those garden essentials that bloom from spring to fall with very little fuss. 1 packet contains - 3gm / 10gm seeds.',
    price: 100,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-verbena-quartz-mix-colors3.jpg',
  ),
  
  Data(
    id: 'i25',
    catid: 'p3',
    title: 'Verbena Quartz',
    description: 'Verbena is one of those garden essentials that bloom from spring to fall with very little fuss. 1 packet contains - 3gm / 10gm seeds.',
    price: 100,
    imageurl:'https://cdnk.nurserylive.com/images/stories/virtuemart/product/nurserylive-verbena-quartz-mix-colors3.jpg',
  ),
  
  
];
